# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ARMORED CORE EXTREME MERCENARIES
email: tooppoo56@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  フロム・ソフトウェア開発のゲーム「アーマードコア」シリーズの非公式discordサーバー「ARMOREDCORE EXTREME MERCENARIES」の情報公開サイトです
domain: "tooppoo.github.io" # the subpath of your site, e.g. /blog
baseurl: "/armoredcore-extreme-mercenaries" # the subpath of your site, e.g. /blog
url: "https://tooppoo.github.io/"
repository: "tooppoo/armoredcore-extreme-mercenaries"
twitter_username: Philomagi
github_username:  tooppoo

show_downloads: false
source: docs

# Build settings
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# options
## http://jekyllrb-ja.github.io/docs/configuration/options/
timezone: Asia/Tokyo
encoding: utf-8

# markdown
kramdown:
  # https://github.com/jekyll/jekyll/issues/8588
  link_defs: >
    {
      invite: ["https://discord.gg/F9HkPsQ37J", "Discordサーバー"],
      question: ["https://discord.com/channels/1240446809906610236/1240455428589223996", "運営への質問"],
      suggestion: ["https://discord.com/channels/1240446809906610236/1240455802272092211", "要望・改善案"],
    }
