packages:
  - packages/*

enablePrePostScripts: false

injectWorkspacePackages: true

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

syncInjectedDepsAfterScripts:
  - build
