minimumReleaseAge: 1440
enablePrePostScripts: false
packages:
  - "packages/*"

# https://pnpm.io/docker#example-2-build-multiple-docker-images-in-a-monorepo
injectWorkspacePackages: true # pnpm deploy のためtrue
syncInjectedDepsAfterScripts:
  - build
