// Generated by Wrangler by running `wrangler types`

interface Env {
	APP_ENV: string;
	SESSION_SECRETS: string;
	AUTH_ACCESS_KEY1: string;
	AUTH_ACCESS_KEY2: string;
	DISCORD_LINK_INVITE: string;
	DISCORD_LINK_QUESTION: string;
	DISCORD_LINK_SUGGESTION: string;
	DISCORD_AUTH_CLIENT_ID: string;
	DISCORD_AUTH_CLIENT_SECRET: string;
	DISCORD_AUTH_CLIENT_CALLBACK: string;
	DB: D1Database;
}
