// Generated by Wrangler on Sun Jan 12 2025 17:27:47 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	DISCORD_LINK_INVITE: string;
	DISCORD_LINK_QUESTION: string;
	DISCORD_LINK_SUGGESTION: string;
}
