import { createPagesFunctionHandler, GetLoadContextFunction } from "@remix-run/cloudflare-pages";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";
import { getLoadContext } from '../load-context'
import { ServerBuild } from '@remix-run/cloudflare';

// workaround
// https://github.com/remix-run/remix/issues/9529#issuecomment-2469743054
const buildWithHackedType = build as unknown as ServerBuild
const getLoadContextHackedType = getLoadContext as unknown as GetLoadContextFunction
export const onRequest = createPagesFunctionHandler({
  build: buildWithHackedType,
  getLoadContext: getLoadContextHackedType,
})
