// Generated by Wrangler by running `wrangler types`

interface Env {
	APP_ENV: string;
	AUTH_UPLOAD_ARCHIVE: string;
	DISCORD_LINK_INVITE: string;
	DISCORD_LINK_QUESTION: string;
	DISCORD_LINK_SUGGESTION: string;
	DB: D1Database;
}
