// Generated by Wrangler by running `wrangler types`

interface Env {
	NODE_ENV: "production";
	TZ: string;
	AUTH_UPLOAD_ARCHIVE: string;
	DISCORD_LINK_INVITE: string;
	DISCORD_LINK_QUESTION: string;
	DISCORD_LINK_SUGGESTION: string;
	YOUTUBE_PUBLIC_DATA_API_KEY: string;
	DB: D1Database;
}
