#:schema node_modules/wrangler/config-schema.json
name = "ac-extreme-mercenaries-test"
main = "./worker.ts"
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat_v2"]

[assets]
binding = "ASSETS"
directory = "./build/client"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "ac-extreme-mercenaries-db-test"
database_id = "test_db"
migrations_dir = "./app/db/migrations"

[[env.test.d1_databases]]
binding = "DB"
database_name = "ac-extreme-mercenaries-db-test"
database_id = "test_db"
migrations_dir = "./app/db/migrations"

[env.test.vars]
# Token used by e2e tests to authorize archive uploads
AUTH_UPLOAD_ARCHIVE = "test_upload_token"
APP_ENV = "test"

MOCK_OGP = "true"
