# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build documents

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # setup runtime
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: 'npm'
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    # integration
    - run: npm ci
    - run: npm run build
    - run: npm test
    # save artifacts
    - uses: actions/upload-artifact@v4
      with:
        name: documents
        path: _site
