# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build documents

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    outputs:
      artifact_name:
        description: "built artifact name, it is ready to deploy"
        value: ${{ jobs.build.outputs.artifact_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.define-artifact-name.outputs.artifact_name }}
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    # setup runtime
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
      with:
        node-version-file: '.node-version'
        cache: 'npm'
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    # integration
    - run: npm ci
    - run: |
        npm run env:generate
        npm run env:apply
      env:
        DISCORD_LINK_INVITE: ${{ vars.DISCORD_LINK_INVITE }}
        DISCORD_LINK_QUESTION: ${{ vars.DISCORD_LINK_QUESTION }}
        DISCORD_LINK_SUGGESTION: ${{ vars.DISCORD_LINK_SUGGESTION }}
    - run: npm run build
    - run: npm test
    # save artifacts
    - name: define artifact name
      id: define-artifact-name
      run: echo "artifact_name=documents-${{ github.sha }}" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
      with:
        name: ${{ steps.define-artifact-name.outputs.artifact_name }}
        path: _site
