name: Deploy Front

on:
  push:
    branches:
      - 'main'
    paths:
      - "packages/front/**"

jobs:
  deploy-front:
    name: deploy front
    runs-on: ubuntu-latest
    environment:
      name: front
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      # setup
      - run: npm ci
      - run: npm run front -- build

      # Migration
      - name: Migration D1
        id: migration-d1
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        continue-on-error: true
        with:
          command: "d1 migrations apply ac-extreme-mercenaries-db --remote"
          apiToken: ${{ secrets.CLOUDFLARE_INTEGRATION }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "packages/front"
      - name: Upload Migration Error
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        if: ${{ steps.migration-d1.outcome == 'failure' }}
        with:
          name: migration-d1-error-log
          path: ./.config/.wrangler/logs/*
      - name: Migration Error
        if: ${{ steps.migration-d1.outcome == 'failure' }}
        run: |
          echo "error on d1 migration"
          exit 1

      # Deploy
      - name: Deploy
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        with:
          command: pages deploy ./build/client
          apiToken: ${{ secrets.CLOUDFLARE_INTEGRATION }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: "packages/front"
