name: Deploy Front

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/front/**"

jobs:
  deploy-front:
    name: deploy front
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: front
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      # setup
      - run: pnpm install --frozen-lockfile
      - run: pnpm run front -- build

      # Migration
      - name: Migration D1
        id: migration-d1
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        continue-on-error: true
        with:
          command: "d1 migrations apply ac-extreme-mercenaries-db --remote"
          apiToken: ${{ secrets.CLOUDFLARE_INTEGRATION }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "packages/front"
      - name: Upload Migration Error
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ steps.migration-d1.outcome == 'failure' }}
        with:
          name: migration-d1-error-log
          path: ./.config/.wrangler/logs/*
      - name: Migration Error
        if: ${{ steps.migration-d1.outcome == 'failure' }}
        run: |
          echo "error on d1 migration"
          exit 1

      # Deploy
      - name: Deploy
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        with:
          command: pages deploy ./build/client
          apiToken: ${{ secrets.CLOUDFLARE_INTEGRATION }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: "packages/front"
