name: Deploy Front

on:
  push:
    branches:
      - 'main'
    paths:
      - "packages/front/**"

jobs:
  deploy-front:
    name: deploy front
    runs-on: ubuntu-latest
    environment:
      name: front
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      # setup
      - run: npm ci
      - run: npm run front -- build

      # Migration
      - name: Migration D1
        id: migration-d1
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        continue-on-error: true
        with:
          command: "d1 migrations apply ac-extreme-mercenaries-db --remote"
          apiToken: ${{ secrets.CLOUDFLARE_INTEGRATION }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "packages/front"
      - name: Upload Migration Error
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ steps.migration-d1.outcome == 'failure' }}
        with:
          name: migration-d1-error-log
          path: ./.config/.wrangler/logs/*
      - name: Migration Error
        if: ${{ steps.migration-d1.outcome == 'failure' }}
        run: |
          echo "error on d1 migration"
          exit 1

      # Deploy
      - name: Deploy
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        with:
          command: pages deploy ./build/client
          apiToken: ${{ secrets.CLOUDFLARE_INTEGRATION }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: "packages/front"
