name: lint and format

on:
  pull_request:
    branches-ignore:
      - 'renovate/*'

jobs:
  lint-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      # setup runtime
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: lint
        run: npm run lint

      - name: auto commit
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
        with:
          commit_message: Auto commit with fmt
          branch: ${{ github.head_ref }}
  reviewdog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        package: [front, discord-bot, e2e]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      # setup runtime
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - run: npm ci
      - run: npm run ${{ matrix.package }} -- build
      - name: reviewdog:${{ matrix.package }}
        uses: reviewdog/action-eslint@2fee6dd72a5419ff4113f694e2068d2a03bb35dd # v1
        with:
          eslint_flags: '"**/*.{ts,tsx,js,jsx}" --fix'
          level: warning
          workdir: packages/${{ matrix.package }}
