name: lint and format

on:
  pull_request:
    branches-ignore:
      - 'renovate/*'

jobs:
  lint-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      # setup runtime
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: lint
        run: npm run lint

      - name: auto commit
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5
        with:
          commit_message: Auto commit with fmt
          branch: ${{ github.head_ref }}
  reviewdog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        package: [front, discord-bot, e2e]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      # setup runtime
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - run: npm ci
      - run: npm run ${{ matrix.package }} -- build
      - name: reviewdog:${{ matrix.package }}
        uses: reviewdog/action-eslint@9b5b0150e399e1f007ee3c27bc156549810a64e3 # v1
        with:
          eslint_flags: '"**/*.{ts,tsx,js,jsx}" --fix'
          level: warning
          workdir: packages/${{ matrix.package }}
